apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: flask-server-scaledobject
  namespace: default
spec:
  scaleTargetRef:
    name: server
  minReplicaCount: 1
  maxReplicaCount: 10
  triggers:
  - type: prometheus
    metadata:
      serverAddress: http://<prometheus-host-ip>:9090
      metricName: flask_server_request_rate
      query: flask_http_request_total
      threshold: '10'
