global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'flask_server'
    static_configs:
      - targets: ['<server-pod-ip>:8080']
    metrics_path: '/metrics'
    honor_labels: true
