global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'flask-app'
    static_configs:
      - targets: ['172.17.0.2:8080'] # IP address of the 'server' docker image which was obtained manually
